import json
import logging
from typing import List
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select

from app.api.deps import get_db, get_current_user
from app.models.user import User
from app.models.competitor_report import CompetitorReport
from app.services.scraping_service import scraping_service
from app.services.seo_service import seo_service
from app.ai_providers import router as ai_router
from app.schemas.competitor import CompetitorAnalysisRequest, CompetitorAnalysisResponse

logger = logging.getLogger(__name__)

router = APIRouter()

@router.post("/analyze", response_model=CompetitorAnalysisResponse)
async def analyze_competitor(
    req: CompetitorAnalysisRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Crawls a competitor website, evaluates SEO, and utilizes AI to summarize keywords, strengths, and content strategies."""
    # 1. Fetch metadata & headings from target website
    crawl_data = await scraping_service.scrape_site(req.website)

    # 2. Run rule-based SEO evaluation
    seo_metrics = seo_service.evaluate_seo(crawl_data)

    # 3. Construct optimization prompt for AI provider
    ai_prompt = (
        f"You are a professional SEO Specialist. Analyze this crawled metadata for website: {req.website}.\n"
        f"Crawl Metrics: {json.dumps(crawl_data)}\n"
        f"SEO Score: {seo_metrics['seo_score']}\n"
        f"Identify primary focus keywords, outline a short content strategy plan, "
        f"list 3 distinct strengths, and 3 weaknesses. "
        f"Return the output in clean JSON format with keys: 'keywords', 'strengths', 'weaknesses', 'opportunities'."
    )

    # 4. Query AI model router
    try:
        ai_resp = await ai_router.route(prompt=ai_prompt, model_name="auto")
        # Try to parse keys from LLM response
        try:
            # Clean string
            text = ai_resp.text.strip()
            if "```json" in text:
                text = text.split("```json")[1].split("```")[0].strip()
            elif "```" in text:
                text = text.split("```")[1].split("```")[0].strip()
            parsed_ai = json.loads(text)
        except Exception:
            parsed_ai = {
                "keywords": seo_metrics["crawl_metrics"].get("meta_keywords", []),
                "strengths": seo_metrics["strengths"],
                "weaknesses": seo_metrics["weaknesses"],
                "opportunities": seo_metrics["opportunities"]
            }
    except Exception as e:
        logger.error(f"AI competitor analysis failed: {e}")
        parsed_ai = {
            "keywords": seo_metrics["crawl_metrics"].get("meta_keywords", []),
            "strengths": seo_metrics["strengths"],
            "weaknesses": seo_metrics["weaknesses"],
            "opportunities": seo_metrics["opportunities"]
        }

    # Consolidated report structure
    report_data = {
        "seo_score": seo_metrics["seo_score"],
        "keywords": parsed_ai.get("keywords", []),
        "meta_tags": {
            "title": crawl_data.get("title", ""),
            "description": crawl_data.get("meta_description", "")
        },
        "social_presence": crawl_data.get("social_links", []),
        "strengths": parsed_ai.get("strengths", seo_metrics["strengths"]),
        "weaknesses": parsed_ai.get("weaknesses", seo_metrics["weaknesses"]),
        "opportunities": parsed_ai.get("opportunities", seo_metrics["opportunities"])
    }

    # 5. Persist to competitor_reports DB table
    report = CompetitorReport(
        user_id=current_user.id,
        website_url=req.website,
        business_name=crawl_data.get("title", req.website)[:100],
        report_json=report_data
    )
    db.add(report)
    await db.commit()

    return report_data

@router.get("/reports", response_model=List[dict])
async def list_reports(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Lists all competitor reports generated by the logged-in user."""
    query = select(CompetitorReport).where(CompetitorReport.user_id == current_user.id).order_by(CompetitorReport.created_at.desc())
    res = await db.execute(query)
    reports = res.scalars().all()
    
    return [
        {
            "id": r.id,
            "website_url": r.website_url,
            "business_name": r.business_name,
            "report": r.report_json,
            "created_at": r.created_at
        }
        for r in reports
    ]
